# Generated by Django 3.0.3 on 2020-02-24 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the control.', max_length=100)),
                ('type', models.CharField(choices=[('Primitive', 'Primitive'), ('CORPSE', 'CORPSE'), ('Gaussian', 'Gaussian'), ('CinBB', 'CinBB'), ('CinSK', 'CinSK')], help_text='Quantum control type.', max_length=30)),
                ('maximum_rabi_rate', models.DecimalField(decimal_places=5, help_text='The maximum achievable angular frequency of the Rabi cycle for a driven quantum transition. Here, this is a number between 0 and 100.', max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('polar_angle', models.DecimalField(decimal_places=5, help_text='An angle measured from the z-axis on the Bloch sphere. This is a number between 0 and 1 (units of pi).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
    ]
